{
 "title": "Metrics Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "actuator_url" }
  ]
 },
 "panels": [
  {
   "title": "API sessions active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions{job=\"java-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg(jvm_memory_used_bytes{job=\"java-api\"}) * 100)/avg(jvm_memory_max_bytes{job=\"java-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"java-api\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(http_server_requests_seconds_sum{job=\"java-api\", status!~\"5.*\", uri!=\"${actuator_url}.*\"}) by (method)\n/\navg(http_server_requests_seconds_count{job=\"java-api\", status!~\"5.*\", uri!=\"${actuator_url}.*\"}) by (method)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}